name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.6.2 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate --schema=prisma/schema.prisma

      - name: Run linter
        run: pnpm lint

      - name: Run TypeScript
        run: pnpm tsc

      - name: Build project
        run: pnpm build
